// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMBVklIgGCdKeAmMVw75PtwX9EH_poQM8',
    appId: '1:1018818356148:web:4007b28730f6bd4ba248e1',
    messagingSenderId: '1018818356148',
    projectId: 'users-management-4ef27',
    authDomain: 'users-management-4ef27.firebaseapp.com',
    storageBucket: 'users-management-4ef27.appspot.com',
    measurementId: 'G-R54YYNS25T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy1UjUTanR1usUA10Z0sgOP_J6O0WC0Hk',
    appId: '1:1018818356148:android:b097dff00792ac67a248e1',
    messagingSenderId: '1018818356148',
    projectId: 'users-management-4ef27',
    storageBucket: 'users-management-4ef27.appspot.com',
  );
}
